include:
  file: trixie-minbase-ab.yaml

image:
  system_part_size: 1500M # Cage + wayland + chromium + deps
  name: mykioskimage

layer:
  app: example-kiosk
  extra: rpi-splash-screen

splash:
  image_path: ${@SRCROOT}/splash.tga

kiosk:
  url: "https://raspberrypi.com"
