device:
  layer: onprem-demo-mydevice
  hostname: OnPremDemoDHCP-INTERNAL
  user1: digilock
  user1pass: Fo0bar!!
  production: false
  wifipass: DigiLink
  
image:
  layer: onprem-demo-myimage
  name: onprem-demo-dhcp-INTERNAL

layer:
  login: login
  docker: docker
  network: net-min
  banner: login-banner
  
