device:
  layer: onprem-demo-mydevice
  hostname: OnPremDemoNetwork-v0.0.4
  production: true
  wifipass: DigiLink 

image:
  layer: onprem-demo-myimage
  name: onprem-demo-network-v0.0.4

layer:
  login: login
  docker: docker
  network: network
  banner: login-banner

