device:
  layer: onprem-demo-mydevice
  hostname: zippy
  user1pass: Fo0bar!!

image:
  layer: onprem-demo-myimage
  name: onprem-demo-network

layer:
  login: login
  docker: docker
  network: network
  banner: login-banner

