device:
  layer: onprem-demo-mydevice
  hostname: OnPremDemoNetwork-INTERNAL
  user1: digilock
  user1pass: Fo0bar!!
  production: false
  wifipass: DigiLink

image:
  layer: onprem-demo-myimage
  name: onprem-demo-network-INTERNAL

layer:
  login: login
  docker: docker
  network: network
  banner: login-banner

