device:
  layer: onprem-demo-mydevice
  hostname: OnPremDemoDHCP-v0.0.4
  production: true
  wifipass: DigiLink

image:
  layer: onprem-demo-myimage
  name: onprem-demo-dhcp-v0.0.4

layer:
  login: login
  docker: docker
  network: net-min
  banner: login-banner
  
